config/routes.rb
Rails.application.routes.draw do
  get '.well-known/acme-challenge/J2vwy8GxBVdTpiCMopCHR3zXOYYoKTYXdOe8T7M1T8E', to: 'static_pages#letsencrypt'
  get 'news', to: 'news_posts#index'
  get 'create_account', to: 'static_pages#create_account'
  get 'faq', to: 'faqs#index'
  get 'sidebar/index'
  namespace :admin do
    get '/', to: 'home#index'
    get '/hired/employees', to: 'employees#hired'
    get '/not_hired/employees', to: 'employees#not_hired'
    post 'hire_employee/:id',to: 'employees#hire',as:'hire_employee'
    get '/events/modal', to: 'events#modal'
    get '/events/camp-id-program', to: 'events#camp_id_program'
    get '/camps/:id/students', to: 'camps#students'
    post '/labs/new-lab', to: 'labs#new_lab', as: 'new_lab'
    resources :accounts
    resources :camps
    resources :employees
    resources :events 
    resources :faqs
    resources :labs
    resources :news_posts
    resources :programs
    resources :students
    resources :users
  end
  resources :coaches
  resources :directors
  resources :labs
  resources :parents
  resources :students, except: [:index] do
    resources :student_applications
  end
  resources :camps, param: :nickname do
    get '/', to:'camps#show'
    get '/staff', to: 'camps#staff'
  end
  resources :accounts, except: [:index]
  resources :site_administrators
  resources :programs
  resources :employees, only: [:new, :edit, :show, :create, :update, :destroy] do
    patch '/avatar_upload', to: 'employees#avatar_upload'
  end
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'static_pages#index'
  get 'static_pages/about'
  
  post 'a/c', to: 'accounts#accountable_change'
  post 'a/p/c', to: 'accounts#create_poly_account'
  get '/apply/(:s)', to: 'accounts#new'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :camp
  belongs_to :program

  validates_presence_of :start_date, on: :create, message: "can't be blank"
  
  def ic_schedule
    IceCube::Schedule.from_hash(self.schedule)
  end

  def start_time
    self.start_date
  end


  # jsonb_accessor :schedule, 
  #   is_recurring: :string,
  #   begins_on: :datetime, 
  #   ends_on: :datetime,
  #   frenquency: :string
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :require_admin
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new(start_date: params.fetch('date'))
    respond_to(:js,:html) 
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    #this is fucking nasty but what you want?
    date = event_params.fetch('start_date').to_time.change({hour:params.fetch('start_time').split(':')[0].to_i,min:params.fetch('start_time').split(':')[1].to_i})

    @event.schedule = IceCube::Schedule.new(date).to_hash

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
        format.js { render :show, notice: 'Event was successfully updated.'}

      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }

      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # RETURN THE PROGRAMS FOR ANY CAMP
  def camp_id_program
    respond_to(:js)
    @programs = Program.where(camp: params['campId'])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :camp_id, :program_id, :start_date, :start_time, :end_time)
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper

end

app/views/admin/events/_form.html.haml
= form_for [:admin, @event], remote:true do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .row.mb-1
    = f.label :name, {class:'col-form-label col-2'}
    .col-10
      = f.text_field :name, {class:'form-control'}
  .row.mb-1
    = f.label :camp, {class:'col-form-label col-2'}
    .col-10
      = f.collection_select :camp_id, Camp.all, :id, :name, {prompt: true},{class:'form-control'}
  .row.mb-1
    = f.label :program, {class:'col-form-label col-2'}
    .col-10
      = f.collection_select :program_id, Program.all, :id, :name,{prompt:"Select a Camp"}, {class:'form-control disabled',disabled:true}
  .row.mb-1
    = f.label :date, {class:'col-form-label col-2'}
    .col-10
      = f.date_field :start_date, {class:'form-control'}
  .row.mb-1
    = f.label :At, {class:'col-form-label col-2'}
    .col-10
      = select_tag :start_time, options_for_select([['Morning','9:30'],['Afternoon','13:00'],['Evening','17:00'],['All Day','00:00']]),{class:'form-control'}
  .row.mb-1
    .form-check
      = label_tag :repeats_check, {class:'form-check-label'} do
        = check_box_tag :repeats_check, 0, false, {class:'form-check-input'}
        Does this event repeat?
  .row.hidden-xs-up.mb-1#event_repeats_info
    .d-flex.justify-content-center
      .monday.p-2.m-2
        M
      .tuesday.p-2.m-2
        T
      .wednesday.p-2.m-2
        W
      .thursday.p-2.m-2
        R
      .friday.p-2.m-2
        F
      .saturday.p-2.m-2
        S
      .sunday.p-2.m-2
        U
  .row.actions.mt-3
    .col-3.offset-9
      = f.submit 'Save', {class:'btn btn-square btn-block btn-success'}

:javascript
  $('#event_camp_id').on('change', function() {
      var params = { campId: $(this).val() };
      $.get('events/camp-id-program', params, function(data) {
          $('#event_program_id').replaceWith(data);
      }, "html");
  });
  $('#repeats_check').change(function(){
    if($(this).is(':checked')){
      $('#event_repeats_info').show().removeClass('hidden-xs-up');
    }else{
      $('#event_repeats_info').hide().addClass('hidden-xs-up');      
    }
  })

app/views/admin/events/camp_id_program.js.erb
<%= select('event', 'program_id', @programs.collect{|p| [ p.name, p.id ]}, {include_blank: "All Programs"}, {class: "form-control"}) %>

app/views/admin/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/admin/events/index.html.haml
%h1 Upcoming events
%p.notice


= month_calendar events: @events do |date,events|
  .date{id: date, style: "height:100px;width:100px;overflow:hidden",data:{startTime:'',endTime:'',date:date}}
    -if(defined? params && date.month == params.fetch('start_date').to_date.month)
      = date.day.to_s(:short)
    -else
      = date.to_s(:short)

    .date-events
      - events.each do |event|
        .event{data:{startTime:'',endTime:''},class:"#{event&.camp&.print_class_name || "camp-wide"}"}
          = event.name 

%table.table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= link_to 'Show', admin_event_url(event)
        %td= link_to 'Edit', edit_admin_event_path(event)
        %td= link_to 'Destroy', admin_event_url(event), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Event', new_admin_event_path
:css
  .prev-month, .next-month{
    opacity:0.5;
  }

app/views/admin/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', admin_events_path

app/views/admin/events/new.js.erb
<%= utnif_modal("Create New Event ") {|t| render 'form', object:Event.new} %>

app/views/admin/events/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/admin/events/show.js.erb
(function() {
    function html(eventClass, eventStartTime, eventEndTime, eventName) {
        var html = "<div class='" + eventClass + " event' data-endtime='" + eventEndTime + "' data-starttime='" + eventStartTime + "'>" + eventName + "</div>";

        return html;
    }
    $('#<%= @event.start_date.to_date %>').find('.date-events').append(html(
        "<%= @event&.camp&.print_class_name %>",
        null,
        null,
        "<%= @event.name %>"
    ));

    $('#utnif-modal').modal('hide');
})(jQuery);