config/routes.rb
Rails.application.routes.draw do
  get '.well-known/acme-challenge/J2vwy8GxBVdTpiCMopCHR3zXOYYoKTYXdOe8T7M1T8E', to: 'static_pages#letsencrypt'
  get 'news', to: 'news_posts#index'
  get 'create_account', to: 'static_pages#create_account'
  get 'faq', to: 'faqs#index'
  get 'sidebar/index'
  namespace :admin do
    get '/', to: 'home#index'
    get '/hired/employees', to: 'employees#hired'
    get '/not_hired/employees', to: 'employees#not_hired'
    post 'hire_employee/:id',to: 'employees#hire',as:'hire_employee'
    get '/events/modal', to: 'events#modal'
    get '/events/camp-id-program', to: 'events#camp_id_program'
    get '/camps/:id/students', to: 'camps#students'
    post '/labs/new-lab', to: 'labs#new_lab', as: 'new_lab'
    resources :accounts
    resources :camps
    resources :employees
    resources :events 
    resources :faqs
    resources :labs
    resources :news_posts
    resources :programs
    resources :students
    resources :users
  end
  resources :coaches
  resources :directors
  resources :labs
  resources :parents
  resources :students, except: [:index] do
    resources :student_applications
  end
  resources :camps, param: :nickname do
    get '/', to:'camps#show'
    get '/staff', to: 'camps#staff'
  end
  resources :accounts, except: [:index]
  resources :site_administrators
  resources :programs
  resources :employees, only: [:new, :edit, :show, :create, :update, :destroy] do
    patch '/avatar_upload', to: 'employees#avatar_upload'
  end
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'static_pages#index'
  get 'static_pages/about'
  
  post 'a/c', to: 'accounts#accountable_change'
  post 'a/p/c', to: 'accounts#create_poly_account'
  get '/apply/(:s)', to: 'accounts#new'
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :students
  has_many :employees, inverse_of: :camp
  has_many :labs
  has_many :programs
  
  has_one :director

  has_attached_file :glossy

  store_accessor :oblique
  validates :name, presence: true
  validates :info, presence: true, length: {minimum: 280, maximum: 1000}
  validates :nickname, presence: true, length: {maximum: 3}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates_attachment_content_type :glossy, content_type: /\Aimage\/.*\z/

  def print_class_name
    self.name.gsub(/[Dd]ebate/,'').parameterize.downcase
  end


end

app/controllers/admin/camps_controller.rb
# Things only administrators can do
class Admin::CampsController < AdminController
  before_action :set_camp, only: [:show, :edit, :update, :destroy, :sign_up, :students]

  respond_to :html, :js



  def index
    @camps = Camp.order(id: :asc)
  end



  def show
  end


  def new
    @camp = Camp.new
  end


  def edit
  end

  def students
    @students = @camp.students
  end
    



  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to admin_camp_path(@camp.id), notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to admin_camp_path(@camp.id), notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to admin_camps_path, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def sign_up
    unless current_user.account
      redirect_to new_account_path
      flash[:alert] = 'You must create an account first'
    end
    a = current_user.account.accountable
    case a
    when a.is_a?(Student)
      then @student = current_user.account.accountable
    else
      @student = Student.new.build_account
    end
  end

  private


  def set_camp
    @camp = Camp.find(params[:id])
  end


  def camp_params
    params.require(:camp).permit(:name,:nickname,:info,:start_date,:end_date,:glossy,:info_blurb,:staff_blurb, oblique: [:main,:one,:two,:three])
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController

  before_action :set_camp, only: [:show,:staff] #, :edit, :update, :destroy, :sign_up, :apply_to_work]
  def show
    if !@camps
      @camps = Camp.all
    end
    
  end

  def staff
    @employees = Employee.where(camp: @camp,is_hired: true)
  end
  private
    def set_camp
      @camp = Camp.find_by(nickname: params[:camp_nickname])
    end


end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_camp_nav.html.haml
- cache do
    - if camp.name
        = link_to camp.name, camp_path(camp.nickname), {"data-target" => "#stage", "data-toggle" => "stage"}

app/views/camps/index.html.haml
%h1 Listing camps

%table.table
  %thead
    %tr
      %th name
      %th nickname
      %th info
      %th starts
      %th ends
      %th
      %th actions
      %th

  %tbody
    - @camps.each do |camp|
      %tr
        %td= camp.name
        %td= camp.nickname
        %td= camp.info[0..50]
        %td= camp.start_date.to_s
        %td= camp.end_date.to_s
        %td= link_to 'Show', camp
        %td= link_to 'Edit', edit_camp_path(camp)
        %td= link_to 'Destroy', camp, :method => :delete, :data => { :confirm => 'Are you sure?' }
        

%br

= link_to 'New Camp', new_camp_path

app/views/camps/show.html.haml
.block.app-block-primary{:style => "background-image: url(#{image_url(@camp.glossy.url)})"}
  .block-lg-middle.block-xs-middle
    .container
      .row
        %h1.block-title.m-b-md
          %span.text-ribbon{class:"text-ribbon-#{@camp.nickname.downcase}"}
            %span
              = @camp.name
          %p.lead
            %span.text-ribbon{class:"text-ribbon-#{@camp.nickname.downcase}"}
              %span 
                =@camp.info.html_safe
- @camp.programs.each do |p|
  %div{:class => cycle('block block-inverse','block')}
    .container
      .row
        .col-xs-12
          %h3
            %span
              = p.name
          %p.lead
            %span
              = simple_format(p.info)

          %p
            %span
              Begins
              = p.start_date.strftime("%B %d, %Y")
              &amp; Ends
              = p.end_date.strftime("%B %d, %Y")
          =link_to "Sign Up for #{p.nickname}", p.old_link, {class:'btn btn-square btn-primary sign-up-link-btn'}

app/views/camps/staff.html.haml
.block.app-block-primary{:style => "background-image: url(#{image_url(@camp.glossy.url)})"}
  .block-lg-middle.block-xs-middle
    .container
      .row
        %h1.block-title.m-b-md
          %span.text-ribbon{class:"text-ribbon-#{@camp.nickname.downcase}"}
            %span
              = @camp.nickname
              Staff
.block-inverse.block-fill-height
  %ul.staff
    - @employees.each do |e|
      %li{style:"background-image:url(#{image_url(e.avatar.url)})"}
        .staff-member
          %h2.staff-name.panel-title.text-serif
            %em
              = e.account.first_name
              = e.account.last_name
          .biog
            %span.text-serif
              = e.bio