config/routes.rb
Rails.application.routes.draw do
  get '.well-known/acme-challenge/J2vwy8GxBVdTpiCMopCHR3zXOYYoKTYXdOe8T7M1T8E', to: 'static_pages#letsencrypt'
  get 'news', to: 'news_posts#index'
  get 'create_account', to: 'static_pages#create_account'
  get 'faq', to: 'faqs#index'
  get 'sidebar/index'
  namespace :admin do
    get '/', to: 'home#index'
    get '/hired/employees', to: 'employees#hired'
    get '/not_hired/employees', to: 'employees#not_hired'
    post 'hire_employee/:id',to: 'employees#hire',as:'hire_employee'
    get '/events/modal', to: 'events#modal'
    get '/events/camp-id-program', to: 'events#camp_id_program'
    get '/camps/:id/students', to: 'camps#students'
    post '/labs/new-lab', to: 'labs#new_lab', as: 'new_lab'
    resources :accounts
    resources :camps
    resources :employees
    resources :events 
    resources :faqs
    resources :labs
    resources :news_posts
    resources :programs
    resources :students
    resources :users
  end
  resources :coaches
  resources :directors
  resources :labs
  resources :parents
  resources :students, except: [:index] do
    resources :student_applications
  end
  resources :camps, param: :nickname do
    get '/', to:'camps#show'
    get '/staff', to: 'camps#staff'
  end
  resources :accounts, except: [:index]
  resources :site_administrators
  resources :programs
  resources :employees, only: [:new, :edit, :show, :create, :update, :destroy] do
    patch '/avatar_upload', to: 'employees#avatar_upload'
  end
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'static_pages#index'
  get 'static_pages/about'
  
  post 'a/c', to: 'accounts#accountable_change'
  post 'a/p/c', to: 'accounts#create_poly_account'
  get '/apply/(:s)', to: 'accounts#new'
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :camp
  
# Program.stduents
  has_many :program_student_assignments
  has_many :students, through: :program_student_assignments

# Program.employees
  has_many :employee_program_assignments
  has_many :employees, through: :employee_program_assignments
  
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < AdminController
  before_action :authenticate_user!
  before_action :set_program, only: [:edit,:show,:destroy,:update]

  def index
    @programs = Program.all
  end

  def new
    @program = Program.new
  end

  def create
    @program = Program.new(program_params)
    
    respond_to do |format|
      if @program.save
        flash[:notice] = 'Program was successfully created.'
        format.html { admin_programs_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    redirect_to action: :edit
  end

  def edit

  end

  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to admin_program_path(@program.id), notice: 'program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to admin_programs_path, notice: 'program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_program
    @program = Program.find(params[:id])
  end
  def program_params
    params.require(:program).permit(:camp_id,:name,:info,:nickname,:price,:start_date,:end_date,:old_link)
  end


end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  









  def show
  end


  def new
    @program = Program.new
    @camps = Camp.all.map {|camp|[camp.nickname,camp.id]}
  end


  def edit
  end



  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


  def set_program
    @program = Program.find(params[:id])
  end


  def program_params
    params.fetch(:program, {})
          .permit(:name, :nickname, :start_date, :end_date, :info, :price, :camp_id)
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/admin/programs/_form.html.haml
= form_for [:admin, @program] do |f|
  - if @program.errors.any?
    #error_explanation
      %h2= "#{pluralize(@program.errors.count, "error")} prohibited this program from being saved:"
      %ul
        - @program.errors.full_messages.each do |msg|
          %li= msg
      #input

  .form-group.row
    = f.label :name, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.text_field :name, {'class'=>'form-control'}
  
  .form-group.row
    = f.label "Curriculum", {class:"col-xs-2 col-form-label"}
    .col-xs-10
      = f.select :camp_id, Camp.all.collect {|c| [ c.name, c.id ] }, {}, {class:"custom-select"}

  .form-group.row
    = f.label :info, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.text_area :info, {'rows'=>'3','class'=>'form-control'}
  
  .form-group.row
    = f.label :nickname, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.text_field :nickname, {'class'=>'form-control'}

  .form-group.row
    = f.label :start_date, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.text_field :start_date, {'type' => 'date','class'=>'form-control'}

  .form-group.row
    = f.label :end_date, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.text_field :end_date, {'type' => 'date','class'=>'form-control'}

  .form-group.row
    = f.label :price, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.number_field :price, {'type' => 'number','class'=>'form-control'}

  .form-group.row
    = f.label :old_link, {'class'=>'col-xs-2 col-form-label'}
    .col-xs-10
      = f.url_field :old_link, {'type' => 'url','class'=>'form-control'}

  .actions
    = f.submit 'Save', {'class'=>'btn btn-primary','type'=>'submit'}

app/views/admin/programs/edit.html.haml
%h1 Editing Program

=render 'form'

app/views/admin/programs/index.html.haml
%h1 Listing Programs
%table.table
  %thead
    %tr
      %th name
      %th nickname
      %th info
      %th starts
      %th ends
      %th
      %th actions
      %th

  %tbody
    - @programs.each do |program|
      %tr
        %td= program.name
        %td= program.nickname
        %td= program.info[0..50]
        %td= program.start_date.to_s
        %td= program.end_date.to_s
        %td= link_to 'Show', program
        %td= link_to 'Edit', edit_admin_program_path(program)
        %td= link_to 'Destroy', admin_program_path(program), :method => :delete, :data => { :confirm => 'Are you sure?' }
        

%br

= link_to 'New program', new_admin_program_path

app/views/admin/programs/new.html.haml
%h1 New Program
%p <em>NB</em>: Program needs to Belong to a camp. (eg. TRI belongs to CX)

= render 'form'

-# = link_to 'Back', admin_camps_path