config/routes.rb
Rails.application.routes.draw do
  get '.well-known/acme-challenge/J2vwy8GxBVdTpiCMopCHR3zXOYYoKTYXdOe8T7M1T8E', to: 'static_pages#letsencrypt'
  get 'news', to: 'news_posts#index'
  get 'create_account', to: 'static_pages#create_account'
  get 'faq', to: 'faqs#index'
  get 'sidebar/index'
  namespace :admin do
    get '/', to: 'home#index'
    get '/hired/employees', to: 'employees#hired'
    get '/not_hired/employees', to: 'employees#not_hired'
    post 'hire_employee/:id',to: 'employees#hire',as:'hire_employee'
    get '/events/modal', to: 'events#modal'
    get '/events/camp-id-program', to: 'events#camp_id_program'
    get '/camps/:id/students', to: 'camps#students'
    post '/labs/new-lab', to: 'labs#new_lab', as: 'new_lab'
    resources :accounts
    resources :camps
    resources :employees
    resources :events 
    resources :faqs
    resources :labs
    resources :news_posts
    resources :programs
    resources :students
    resources :users
  end
  resources :coaches
  resources :directors
  resources :labs
  resources :parents
  resources :students, except: [:index] do
    resources :student_applications
  end
  resources :camps, param: :nickname do
    get '/', to:'camps#show'
    get '/staff', to: 'camps#staff'
  end
  resources :accounts, except: [:index]
  resources :site_administrators
  resources :programs
  resources :employees, only: [:new, :edit, :show, :create, :update, :destroy] do
    patch '/avatar_upload', to: 'employees#avatar_upload'
  end
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'static_pages#index'
  get 'static_pages/about'
  
  post 'a/c', to: 'accounts#accountable_change'
  post 'a/p/c', to: 'accounts#create_poly_account'
  get '/apply/(:s)', to: 'accounts#new'
end

app/views/layouts/admin/_events.html.haml
%h1 4 Day Snapshot
%p upcoming events
%p Event 1
%p Event 2
%p Event 3

app/views/layouts/admin/_sidebar.html.haml
.col-sm-3.col-md-2.pt-5.sidebar.mh
    = link_to admin_path do
        %span.text-ribbon.text-ribbon-danger.text-black
            %span WELCOME TO THE ADMIN SPACE
        %br/
        %br/
        %span.text-ribbon.text-ribbon-transparent.text-white
            %span From here you can do all kinds of damage, so please try to be careful!

    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header About You
        .nav-item.active
            =link_to "Admin Home", admin_path, {class:"nav-link active"}
        .nav-item
            =link_to "Email Dorm Staff", nil, {class:"nav-link"}
        .nav-item
            =link_to "Email All Staff",nil, {class:"nav-link"}
        .nav-item
            =link_to "Calendar",admin_events_path, {class:"nav-link"}

    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Students
        .nav-item
            =link_to "List All Students", admin_students_path, {class:"nav-link"}
        .nav-item
            =link_to "Dorm Rooms",nil, {class:"nav-link"}

    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Employees
        .nav-item
            =link_to "List All Employees", admin_employees_path, {class:"nav-link"}

    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Camps
        .nav-item
            =link_to "List Camps", admin_camps_path, {class:"nav-link"}

    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Programs
        .nav-item
            =link_to "List programs", admin_programs_path, {class:"nav-link"}
            
    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Labs
        .nav-item
            =link_to "List Labs", admin_labs_path, {class:"nav-link"}
            
    .nav.flex-column.nav-sidebar.mt-2
        %small.nav-header Website Stuff
        .nav-item
            =link_to "Blog Posts", admin_news_posts_path, {class:"nav-link"}
        .nav-item
            =link_to "Faqs", admin_faqs_path, {class:"nav-link"}


    

app/views/layouts/admin/application.html.haml
!!! 5
%html.admin
  %head
    %title utnif
    %meta{ :name => "description", :content => "" }
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %meta{ :charset => "UTF-8" }
    =# favicon_link_tag
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags

    :plain
      <script type="text/javascript" src="//d3js.org/d3.v3.min.js"></script>
      <script type="text/javascript" src="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" />

      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
      <style>
        @media (max-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
          body {
            width: 1px;
            min-width: 100%;
            *width: 100%;
          }
          #stage {
            height: 1px;
            overflow: auto;
            min-height: 100vh;
            -webkit-overflow-scrolling: touch;
          }
        }
      </style>

  %body.admin{:style => "overflow: auto;"}
    .container-fluid.h-100
      .row
        = render 'layouts/admin/sidebar'
        - flash.each do |type, message|
          .alert.alert-dismissable{ :class => utnif_type(type) }
            = message
        .col-sm-9.col-md-10.pt-5
          = yield



      #m
      = javascript_include_tag "application"
      :javascript
        +function ($) {
          $('.alert.alert-dismissable').delay(2000).slideUp("slow");
          $('[data-toggle="tooltip"]').tooltip({placement: 'top',trigger: 'manual'}).tooltip('show');
          $('[data-toggle="tooltip"]').click(function(){
            $(this).tooltip('hide');
          });
        }(jQuery);